### GET ONE ART RECORD

GET http://localhost:3000/api/art/20830

### GET LIST OF ARTS FILTER BY TYPE

GET http://localhost:3000/api/art?type=fastyyyyy

#### ADD COMMENT TO AN ART RECORD

POST http://localhost:3000/api/art/20830/comments
Content-Type: application/json

{
  "name": "Raymon1",
  "content": "This is a short comment2",
  "artId": "20830"
}

### LIST ALL USERS

GET http://localhost:3000/api/users

### CREATE AN USER

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "R1aya111a1mo1n3",
  "age": 25,
  "location": "dsdsd"
}